#!/bin/bash
# Author Yen Hoang, M.Sc.
# 2013

mkdir /project/results/me/WGS/CN_FF/genotyper/anno
cd /project/results/me/WGS/CN_FF/genotyper/
echo "START INDEL ANALYSIS 2 bwa_default"
echo "######## GATK UnifiedGenotyper --> SNP/INDEL Calling CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T UnifiedGenotyper	\
 -nt 5			\
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -D /project/data/refs/b37/VCF/dbsnp_135.b37.vcf			\
 -glm BOTH	\
 -I /project/results/me/WGS/CN_FF/gatk/CN_FFgen.bwa.reduced.bam \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.raw.vcf	
echo " "
echo "##### GATK SelectVariants --> Select only InDels CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T SelectVariants \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.raw.vcf	 \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_raw.vcf	 \
 -selectType INDEL
echo ""
echo "##### GATK UnifiedGenotyper --> VariantRecalibrator CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantRecalibrator \
 -nt 5                  \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -resource:mills,known=false,training=true,truth=true,prior=12.0 /project/data/refs/b37/VCF/Mills_and_1000G_gold_standard.indels.b37.sites.vcf \
 -resource:dbsnp,known=true,training=false,truth=false,prior=2.0 /project/data/refs/b37/VCF/dbsnp_135.b37.vcf \
 -an DP -an FS -an ReadPosRankSum -an MQRankSum \
 -mode INDEL            	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_raw.vcf	\
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_recal  	\
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_tranches	\
 -rscriptFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_r    
echo " "
echo "##### GATK UnifiedGenotyper --> Apply Recalibration CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T ApplyRecalibration  \
 --ts_filter_level 99.0 \
 mode INDEL		\
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_raw.vcf            \
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_recal          \
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_tranches    \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_recal.vcf      
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_recal.vcf |grep 'PASS' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_pass.vcf
echo ""
echo "##### GATK VariantFiltration Mapqual: DP >= 13 && MQ >= 43.0 CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantFiltration \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta \
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_recal.vcf \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_filtered.vcf \
 --filterExpression "DP >= 13 && MQ >= 43.0" \
 --filterName "q43cov13" 
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_filtered.vcf |grep 'q43cov13' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_q43cov13.vcf
echo ""
echo "##### ANNOVAR CN_FFgen"
cd /project/results/me/WGS/CN_FF/genotyper/anno/
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_pass.vcf >CN_FFgen.bwa.ug.indel_pass
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.indel_q43cov13.vcf >CN_FFgen.bwa.ug.indel_q43cov13
/analyse_bin/annovar/summarize_gatk_indel.pl --remove --step 1,4,9 CN_FFgen.bwa.ug.indel_pass -outfile CN_FFgen.bwa.ug.indel_pass /analyse_bin/annovar/humandb/
/analyse_bin/annovar/summarize_gatk_indel.pl --remove --step 1,4,9 CN_FFgen.bwa.ug.indel_q43cov13 -outfile CN_FFgen.bwa.ug.indel_q43cov13 /analyse_bin/annovar/humandb/
echo "DONE WITH INDEL2 CN_FFgen"
echo ""
echo "START SNP ANALYSIS bwa_default"
cd /project/results/me/WGS/CN_FF/genotyper/
echo "##### GATK SelectVariants --> Select only SNPs CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T SelectVariants \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.raw.vcf	 \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_raw.vcf	 \
 -selectType SNP
echo ""
echo "##### GATK UnifiedGenotyper --> VariantRecalibrator CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantRecalibrator \
 -nt 5                  \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -resource:hapmap,known=false,training=true,truth=true,prior=15.0 /project/data/refs/b37/VCF/hapmap_3.3.b37.sites.vcf     \
 -resource:omni,known=false,training=true,truth=false,prior=12.0 /project/data/refs/b37/VCF/1000G_omni2.5.b37.sites.vcf   \
 -resource:dbsnp,known=true,training=false,truth=false,prior=6.0 /project/data/refs/b37/VCF/dbsnp_135.b37.vcf             \
 -an QD -an MQ -an DP -an MQRankSum -an ReadPosRankSum -an FS		\
 -mode SNP            	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_raw.vcf		\
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_recal  	\
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_tranches	\
 -rscriptFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_r    
echo " "
echo "##### GATK UnifiedGenotyper --> Apply Recalibration CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T ApplyRecalibration  \
 --ts_filter_level 99.0 \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_raw.vcf            \
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_recal          \
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_tranches    \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_recal.vcf      
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_recal.vcf |grep 'PASS' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_pass.vcf
echo ""
echo "##### GATK VariantFiltration Mapqual: DP >= 13 && MQ >= 43.0 CN_FFgen"
java -Xmx54g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantFiltration \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta \
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_recal.vcf	\
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_filtered.vcf	\
 --filterExpression "DP >= 13 && MQ >= 43.0" \
 --filterName "q43cov13" 
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_filtered.vcf |grep 'q43cov13' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_q43cov13.vcf
echo ""
echo "##### ANNOVAR CN_FFgen"
cd /project/results/me/WGS/CN_FF/genotyper/anno/
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_pass.vcf >CN_FFgen.bwa.ug.snp_pass
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.ug.snp_q43cov13.vcf >CN_FFgen.bwa.ug.snp_q43cov13
/analyse_bin/annovar/summarize_gatk_snp.pl --remove --step 1,4,9 CN_FFgen.bwa.ug.snp_pass -outfile CN_FFgen.bwa.ug.snp_pass /analyse_bin/annovar/humandb/
/analyse_bin/annovar/summarize_gatk_snp.pl --remove --step 1,4,9 CN_FFgen.bwa.ug.snp_q43cov13 -outfile CN_FFgen.bwa.ug.snp_q43cov13 /analyse_bin/annovar/humandb/
echo "DONE WITH SNP CN_FFgen"
echo ""

cd /project/results/me/WGS/CN_FF/genotyper/
echo "START INDEL ANALYSIS HAPLOTYPE CALLER bwa_default"
cd /project/results/me/WGS/CN_FF/genotyper/
echo "######## GATK HaplotypeCaller --> INDEL/SNP Calling CN_FFgen"
java -Xmx24g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T HaplotypeCaller	\
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -D /project/data/refs/b37/VCF/dbsnp_135.b37.vcf			\
 -I /project/results/me/WGS/CN_FF/gatk/CN_FFgen.bwa.reduced.bam 	\
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.raw.vcf	
echo " "
echo "##### GATK SelectVariants --> Select only InDels CN_FFgen"
java -Xmx24g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T SelectVariants \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.raw.vcf \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_raw.vcf \
 -selectType INDEL
date
echo "##### GATK HaplotypeCaller --> VariantRecalibrator CN_FFgen"
java -Xmx24g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantRecalibrator \
 -nt 5                  \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -resource:mills,known=false,training=true,truth=true,prior=12.0 /project/data/refs/b37/VCF/Mills_and_1000G_gold_standard.indels.b37.sites.vcf \
 -resource:dbsnp,known=true,training=false,truth=false,prior=2.0 /project/data/refs/b37/VCF/dbsnp_135.b37.vcf \
 -an DP -an FS -an ReadPosRankSum -an MQRankSum \
 -mode INDEL            	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_raw.vcf	\
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_recal  	\
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_tranches	\
 -rscriptFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_r    
echo " "
date
echo "##### GATK HaplotypeCaller --> Apply Recalibration CN_FFgen"
java -Xmx24g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T ApplyRecalibration  \
 --ts_filter_level 99.0 \
 -mode INDEL            	\
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta	\
 -input /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_raw.vcf            \
 -recalFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_recal          \
 -tranchesFile /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_tranches    \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_recal.vcf      
echo " "
date
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_recal.vcf |grep 'PASS' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_pass.vcf
echo ""
date
echo "##### GATK VariantFiltration Mapqual: DP >= 13 && MQ >= 43.0 CN_FFgen"
java -Xmx24g -jar /analyse_bin/GATK/2.5-2/GenomeAnalysisTK.jar \
 -T VariantFiltration \
 -R /project/data/refs/b37/Sequences/WholeGenome/human_g1k_v37.fasta \
 --variant /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_recal.vcf \
 -o /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_filtered.vcf \
 --filterExpression "DP >= 13 && MQ >= 43.0" \
 --filterName "q43cov13" 
more /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_filtered.vcf |grep 'q43cov13' >/project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_q43cov13.vcf
echo ""
echo "##### ANNOVAR CN_FFgen"
cd /project/results/me/WGS/CN_FF/genotyper/anno/
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_pass.vcf >CN_FFgen.bwa.hapC.indel_pass
/analyse_bin/annovar/convertgatk2annovar.pl -format vcf4 /project/results/me/WGS/CN_FF/genotyper/CN_FFgen.bwa.hapC.indel_q43cov13.vcf >CN_FFgen.bwa.hapC.indel_q43cov13
/analyse_bin/annovar/summarize_gatk_indel.pl --remove --step 1,4,9 CN_FFgen.bwa.hapC.indel_pass -outfile CN_FFgen.bwa.hapC.indel_pass /analyse_bin/annovar/humandb/
/analyse_bin/annovar/summarize_gatk_indel.pl --remove --step 1,4,9 CN_FFgen.bwa.hapC.indel_q43cov13 -outfile CN_FFgen.bwa.hapC.indel_q43cov13 /analyse_bin/annovar/humandb/
echo "DONE WITH INDEL CN_FFgen"
echo ""
echo ""
echo "DONE WITH WORKFLOW CN_FFgen"

